CUDA Device Index: 1
dataset is  dgl cora
  NumNodes: 2708
  NumEdges: 5278
  NumFeats: 1433
  NumClasses: 7
  NumTrainingSamples: 140
  NumValidationSamples: 500
  NumTestSamples: 1000
Done loading data from cached files.
dataset is  dgl cora
  NumNodes: 2708
  NumEdges: 5278
  NumFeats: 1433
  NumClasses: 7
  NumTrainingSamples: 140
  NumValidationSamples: 500
  NumTestSamples: 1000
Done loading data from cached files.
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/main.py", line 256, in <module>
    data, data_x, data_y, edges, num_features, data_train_maskOrigin, data_val_maskOrigin, data_test_maskOrigin = load_dataset()
                                                                                                                  ^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/main.py", line 163, in load_dataset
    data = data.to(device)
           ^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/heterograph.py", line 5709, in to
    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/heterograph_index.py", line 255, in copy_to
    return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dgl/_ffi/_cython/./function.pxi", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 227, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 217, in dgl._ffi._cy3.core.FuncCall3
dgl._ffi.base.DGLError: [18:08:19] /opt/dgl/src/runtime/c_runtime_api.cc:82: Check failed: allow_missing: Device API cuda is not enabled. Please install the cuda version of dgl.
Stack trace:
  [bt] (0) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x75) [0x7fec963d58f5]
  [bt] (1) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(dgl::runtime::DeviceAPIManager::GetAPI(std::string, bool)+0x202) [0x7fec96744a92]
  [bt] (2) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(dgl::runtime::DeviceAPI::Get(DGLContext, bool)+0x1e1) [0x7fec96741071]
  [bt] (3) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DGLDataType, DGLContext)+0x13b) [0x7fec9675c54b]
  [bt] (4) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyTo(DGLContext const&) const+0xc3) [0x7fec96796d53]
  [bt] (5) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(dgl::UnitGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0x3ff) [0x7fec968a424f]
  [bt] (6) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(dgl::HeteroGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0xf6) [0x7fec967a35d6]
  [bt] (7) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(+0x51b396) [0x7fec967b2396]
  [bt] (8) /home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7fec967402a8]


