cuda Device Index: 1
Namespace(to_undirected=False, from_SHA=False, IsDirectedData=False, AugDirect=0, net='SAGE', GPUdevice=1, seed=100, undirect_dataset='Coauthor-CS', Direct_dataset='dgl/', imb_ratio=100, dropout=0.1, num_filter=2, layer=2, alpha=0.1, K=2, feat_dim=64, warmup=5, epoch=1500, lr=0.01, l2=0.0005, tau=2, max=False, no_mask=False, gdc='ppr', heads=8, log_root='../logs/', log_path='test', data_path='../dataset/data/tmp/')
The Dataset is  CoauthorCS() from DirectedData:  False
Num_bidirect_edges: 81894, total_num_edges: 163788
This is directed graph:  False
data_x torch.Size([18333, 6805])
Traceback (most recent call last):
  File "/home/qj2004/GraphSHA/DiGMain.py", line 331, in <module>
    val_loss = train(train_idx, edge_in, in_weight, edge_out, out_weight, SparseEdges, edge_weight)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/DiGMain.py", line 39, in train
    out = model(data_x, edges)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/GraphSHA/nets/geometric_baselines.py", line 465, in forward
    x = self.conv1(x, edge_index)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.conda/envs/env3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.local/lib/python3.11/site-packages/torch_geometric/nn/conv/sage_conv.py", line 130, in forward
    out = self.propagate(edge_index, x=x, size=size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.local/lib/python3.11/site-packages/torch_geometric/nn/conv/message_passing.py", line 455, in propagate
    coll_dict = self._collect(self._user_args, edge_index, size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.local/lib/python3.11/site-packages/torch_geometric/nn/conv/message_passing.py", line 329, in _collect
    data = self._lift(data, edge_index, dim)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qj2004/.local/lib/python3.11/site-packages/torch_geometric/nn/conv/message_passing.py", line 276, in _lift
    raise e
  File "/home/qj2004/.local/lib/python3.11/site-packages/torch_geometric/nn/conv/message_passing.py", line 266, in _lift
    return src.index_select(self.node_dim, index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.15 GiB. GPU 1 has a total capacty of 23.69 GiB of which 569.69 MiB is free. Process 80897 has 7.62 GiB memory in use. Process 81003 has 13.47 GiB memory in use. Including non-PyTorch memory, this process has 2.03 GiB memory in use. Of the allocated memory 1.72 GiB is allocated by PyTorch, and 20.82 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
